exports.seed = (knex, Promise) => {
  return knex('houses').insert([
    { id: 0,
      name: 'Alexandra',
      gfa: '170.69m2',
      cost: '$396,600.00',
      description: '',
      image_cover: './img/houses/alexandra/alexandra.png',
      image_plan: './img/houses/alexandra/alexandra_floor.png',
      image_3d: './img/houses/alexandra/alexandra_3d.png',
      image_elevations: './img/houses/alexandra/alexandra_elevation.png'
    },
    { id: 1,
      name: 'Andrew',
      gfa: '148.56m2',
      cost: '$347,690.00',
      description: '',
      image_cover: './img/houses/andrew/andrew.png',
      image_plan: './img/houses/andrew/andrew_plan.png',
      image_3d: './img/houses/andrew/andrew_3d.png',
      image_elevations: './img/houses/andrew/andrew_elevation.png'
    },
    { id: 2,
      name: 'Anne',
      gfa: '166.61m2',
      cost: '$386,565.00',
      description: '',
      image_cover: './img/houses/anne/anne.png',
      image_plan: './img/houses/anne/anne_floor.png',
      image_3d: './img/houses/anne/anne_3d.png',
      image_elevations: './img/houses/anne/anne_elevation.png'
    },
    { id: 3,
      name: 'Catherine',
      gfa: '111.08m2',
      cost: '$287,079.00',
      description: '',
      image_cover: './img/houses/catherine/catherine.png',
      image_plan: './img/houses/catherine/catherine_floor.png',
      image_3d: './img/houses/catherine/catherine_3d.png',
      image_elevations: './img/houses/catherine/catherine_elevation.png'
    },
    { id: 4,
      name: 'Charles',
      gfa: '181.76m2',
      cost: '$410,903.00',
      description: '',
      image_cover: './img/houses/charles/charles.png',
      image_plan: './img/houses/charles/charles_floor.png',
      image_3d: './img/houses/charles/charles_3d.png',
      image_elevations: './img/houses/charles/charles_elevation.png'
    },
    { id: 5,
      name: 'Charlotte',
      gfa: '135.37m2',
      cost: '$339,160.00',
      description: '',
      image_cover: './img/houses/charlotte/charlotte.png',
      image_plan: './img/houses/charlotte/charlotte_floor.png',
      image_3d: './img/houses/charlotte/charlotte_3d.png',
      image_elevations: './img/houses/charlotte/charlotte_elevation.png'
    },
    { id: 6,
      name: 'Edward 2',
      gfa: '106.41m2',
      cost: '$281,894.00',
      description: '',
      image_cover: './img/houses/edward2/edward2.png',
      image_plan: './img/houses/edward2/edward2_floor.png',
      image_3d: './img/houses/edward2/edward2_3d.png',
      image_elevations: './img/houses/edward2/edward2_elevation.png'
    },
    { id: 7,
      name: 'Edward 3',
      gfa: '120.22m2',
      cost: '$318,056.00',
      description: '',
      image_cover: './img/houses/edward3/edward3.png',
      image_plan: './img/houses/edward3/edward3_floor.png',
      image_3d: './img/houses/edward3/edward3_3d.png',
      image_elevations: './img/houses/edward3/edward3_elevation.png'
    },
    { id: 8,
      name: 'Edward 4',
      gfa: '132.71m2',
      cost: '$338,712.00',
      description: '',
      image_cover: './img/houses/edward4/edward4.png',
      image_plan: './img/houses/edward4/edward4_floor.png',
      image_3d: './img/houses/edward4/edward4_3d.png',
      image_elevations: './img/houses/edward4/edward4_elevation.png'
    },
    { id: 9,
      name: 'Ernest',
      gfa: '167.62m2',
      cost: '$384,059.00',
      description: '',
      image_cover: './img/houses/ernest/ernest.png',
      image_plan: './img/houses/ernest/ernest_floor.png',
      image_3d: './img/houses/ernest/ernest_3d.png',
      image_elevations: './img/houses/ernest/ernest_elevation.png'
    },
    { id: 10,
      name: 'George',
      gfa: '166.04m2',
      cost: '$382,386.00',
      description: '',
      image_cover: './img/houses/george/george.png',
      image_plan: './img/houses/george/george_floor.png',
      image_3d: './img/houses/george/george_3d.png',
      image_elevations: './img/houses/george/george_elevation.png'
    },
    { id: 11,
      name: 'James',
      gfa: '164.84m2',
      cost: '$374,792.00',
      description: '',
      image_cover: './img/houses/james/james.png',
      image_plan: './img/houses/james/james_floor.png',
      image_3d: './img/houses/james/james_3d.png',
      image_elevations: './img/houses/james/james_elevation.png'
    },
    { id: 12,
      name: 'Louis',
      gfa: '158.11m2',
      cost: '$375,133.00',
      description: '',
      image_cover: './img/houses/louis/louis.png',
      image_plan: './img/houses/louis/louis_floor.png',
      image_3d: './img/houses/louis/louis_3d.png',
      image_elevations: './img/houses/louis/louis_elevation.png'
    },
    { id: 13,
      name: 'Mary',
      gfa: '165.25m2',
      cost: '$364,510.00',
      description: '',
      image_cover: './img/houses/mary/mary.png',
      image_plan: './img/houses/mary/mary_floor.png',
      image_3d: './img/houses/mary/mary_3d.png',
      image_elevations: './img/houses/mary/mary_elevation.png'
    },
    { id: 14,
      name: 'Victoria',
      gfa: '180.97m2',
      cost: '$392,262.00',
      description: '',
      image_cover: './img/houses/victoria/victoria.png',
      image_plan: './img/houses/victoria/victoria_floor.png',
      image_3d: './img/houses/victoria/victoria_3d.png',
      image_elevations: './img/houses/victoria/victoria_elevation.png'
    },
    { id: 15,
      name: 'William',
      gfa: '201.97m2',
      cost: '$428,062.00',
      description: '',
      image_cover: './img/houses/william/william.png',
      image_plan: './img/houses/william/william_floor.png',
      image_3d: './img/houses/william/william_3d.png',
      image_elevations: './img/houses/william/william_elevation.png'
    },
  ])
}
